### ISSUE TITLE
Position of SemiCircle is not updated

### ISSUE THREAD

**Issue by igorskh** [clementallen/react-leaflet-semicircle#51]
Hi,

I have problem with updating the position of `SemiCircle`.

After the component has been initially rendered, I am updating using `setState` properties: `position`, `stopAngle`, `startAngle`. It works fine with angles, but not with the position, the marker stays on the initial position regardless of the value.

Any idea what the problem could be?

Here is the sample code: https://codesandbox.io/s/polished-grass-mtpr7
(Clicking big `next` button show iterate over positions to see the effect).

Thanks.

**Comment by clementallen** [comment]
Thanks for the report @igorskh and the excellent codesandbox to reproduce it!

I've published a fix in v2.0.9 which looks to be working: https://codesandbox.io/s/xenodochial-zhukovsky-4cs9m

Please let me know if it does for you too 👍

**Comment by igorskh** [comment]
Hey,

Thanks for the fast reply and the fix,

I have few comments here: #53
