### ISSUE TITLE
SemiCircle not working with Popup element

### ISSUE THREAD

**Issue by JuanQP** [clementallen/react-leaflet-semicircle#73]
This:
```jsx
<Circle
  center={/*Some center*/}
  radius={/*Some radius*/}
>
  <Popup>
    Some description
  </Popup>
</Circle>
```
will work as expected: Popup will interact with the Circle component.

But this:
```jsx
<SemiCircle
  position={/*Some center*/}
  radius={/*Some radius*/}
>
  <Popup>
    Some description
  </Popup>
</SemiCircle>
```
won't work as expected. As far as I know, Popup isn't receiving information from SemiCircle component. I don't know if this is intended, but having this feature would be great in order to have the same functionality with the other components.

**Comment by clementallen** [comment]
Great! Glad to hear
