### ISSUE TITLE
pathOptions for semi-circle

### ISSUE THREAD

**Issue by adrwstn** [clementallen/react-leaflet-semicircle#79]
How can I submit path options to semi-circle such as fill color?

**Comment by clementallen** [comment]
All [path options](https://leafletjs.com/SlavaUkraini/reference.html#circle-fillcolor) can be passed to `<SemiCircle />` as props.

Example:
```javascript
<SemiCircle position={[lat, lng]} fillColor="orange" fillOpacity={0.5} />
```

Please feel free to close this issue if this resolves your query!

**Comment by adrwstn** [comment]
here I am trying to figure out why pathOptions prop wasn't working... you're awesome, thanks!
